version: '2'
services:
  nginx:
    image: nginx:1.9.6
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:8000"
    volumes_from:
      - frontend
    depends_on:
      - backend

  mongo:
    image: mongo:3.2
    volumes:
      - mongoDB:/data/db

  backend:
    image: coderdojomaster/backend
    environment:
      MONGO_HOST: "mongo"
      MONGO_USERNAME: ""
      MONGO_PASSWORD: ""
      MONGO_DBNAME: "development"
      DEVELOPMENT: "true"

  frontend:
    build:
      context: ./
      dockerfile: ./Dockerfile_dev
    command: gulp
    working_dir: /data
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./:/data
volumes:
  mongoDB: {}